title: "Generativní AI"
description: "Materiály ke cvičením předmětu Generativní AI (AI Bridge, KII PEF ČZU)"
url: "https://pesout.github.io"
baseurl: "/gen-ai"

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
